### ISSUE TITLE
Cert Manager Operator Missing from OpenShift 4.18 Release Candidate

### ISSUE THREAD

**Issue by cgruver** [openshift/cert-manager-operator-release#105]
I just built a new cluster from `quay.io/openshift-release-dev/ocp-release:4.18.0-rc.1-x86_64`

The Cert Manager Operator is not in the catalog.

```yaml
apiVersion: v1                      
kind: Namespace                 
metadata:
  name: cert-manager-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-cert-manager-operator
  namespace: cert-manager-operator
spec:
  targetNamespaces:
  - cert-manager-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-cert-manager-operator
  namespace: cert-manager-operator
spec:
  channel: stable-v1
  name: openshift-cert-manager-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
```

Applying the above will result in a failed install because the operator source cannot be found.
